# Generated by Django 4.2.24 on 2025-11-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0003_department_studentid_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.TextField(default=None),
        ),
    ]
