# Generated by Django 4.2.24 on 2026-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipeapp', '0004_student_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
